# Generated by Django 5.1.6 on 2025-02-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_catigory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catigory',
        ),
    ]
