# Generated by Django 5.1.6 on 2025-03-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': []},
        ),
    ]
